### ISSUE TITLE
Add support on lower linux versions

### ISSUE THREAD

**Issue by uwuclxdy** [BitpingApp/Bitping-Node#12]
Tried to install new bitping node on Ubuntu server 16 and 18 and it is telling me that I'm missing some libraries which can be solved with a version update. Let me know if there is some confusion or if any screenshots are needed.

**Comment by Firaenix** [comment]
We use Debian 11 to build all of our binaries, which pins us to that version of GLIBC, we don't plan to support lower versions as it would break the build for our desktop builds. Maybe we can reconsider this in future
