### ISSUE TITLE
Bitping DNS Issues

### ISSUE THREAD

**Issue by engageub** [BitpingApp/Bitping-Node#15]
Hi Support Team,
Bitping login is working with google dns (8.8.8.8, 8.8.4.4) but not other DNS like cloudflare.
The following errors are thrown when using cloudflare and oracle dns are used.
Could you please look into this and update your urls. 

CloudFlare DNS (1.1.1.1 ,1.0.0.1)

```
docker.io/bitping/bitpingd:latest
⢀⠀ Logging into Bitping...Error: GRPC Error: status: Unavailable, message: "error trying to connect: tcp connect error: Address not available (os error 99)", details: [], metadata: MetadataMap { headers: {} }

```

Oracle DNS
```
docker.io/bitping/bitpingd:latest
⢃⠀ Logging into Bitping...Error: GRPC Error: status: Internal, message: "protocol error: received message with invalid compression flag: 60 (valid flags are 0 and 1) while receiving response with status: 403 Forbidden", details: [], metadata: MetadataMap { headers: {"date": "Mon, 15 Jan 2024 21:34:47 GMT", "content-type": "text/html; charset=UTF-8", "x-frame-options": "SAMEORIGIN", "referrer-policy": "same-origin", "cache-control": "max-age=15", "expires": "Mon, 15 Jan 2024 21:35:02 GMT", "report-to": "{\"endpoints\":[{\"url\":\"https:\/\/a.nel.cloudflare.com\/report\/v3?s=4uc7p5wpbZqxA%2BH9vxV6SiLdL10j9jDf131thKlBXf9c2JBmtx%2Bck8A30V3Oq2yVOhz5O0OCpVH6G4zmJ%2BhzIn0vwHztcqjEKP2QHgcY7E3WZGb4slmhRNW6PiS4S2qJ%2BcDP\"}],\"group\":\"cf-nel\",\"max_age\":604800}", "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}", "vary": "Accept-Encoding", "server": "cloudflare", "cf-ray": "84613eacfe6799bc-CDG", "alt-svc": "h3=\":443\"; ma=86400"} }

```

Thank you

**Comment by engageub** [comment]
Hi Support Team,
Could you please update on this.

Thank you

**Comment by Firaenix** [comment]
Oracle cloud has been blocked by our Cloudflare due to DDoS being detected from that ASN. I recommend switching VPS providers for now

**Comment by engageub** [comment]
Hi,
The problem is with DNS. If I use google dns 8.8.8.8 and 8.8.4.4, it works fine. Its not about switching VPS. 

Thank you

**Comment by Firaenix** [comment]
Our DNS is hosted on Cloudflare, so not sure why it wouldnt be showing up there. We dont have any control over who propagates our DNS records or not but thanks for making us aware of the issue.
