### ISSUE TITLE
[arm64] Bitpingd docker instance shows up in dashboard with "Failed to execute HTTP requests"

### ISSUE THREAD

**Issue by rcky844** [BitpingApp/Bitping-Node#19]
As specified in the title, the instance ran on a device with more than 256M of RAM cannot execute HTTP requests and shows up with "Node issues".

![image](https://github.com/user-attachments/assets/e734b1fc-a4e7-4762-8cd0-3455dacf9c96)

**Comment by Firaenix** [comment]
Hi, is this still happening?

If you hover over the individual icons what does it say in the pop-up?

**Comment by rcky844** [comment]
> Hi, is this still happening?
> 
> If you hover over the individual icons what does it say in the pop-up?

It states the message as in the title of this issue.
I have since taken down this instance though.

**Comment by Firaenix** [comment]
No worries in regards to taking the node offline.

I was wondering if any of the other protocols had any extra information as you only mentioned HTTP but providing ICMP and DNS data helps me diagnose the issue further.

If you end up running the node again to test, let me know.
