### ISSUE TITLE
[Feature Request] Email and Password in docker

### ISSUE THREAD

**Issue by engageub** [BitpingApp/Bitping-Node#7]
Hi Support Team,
Could you please provide option to enter email address and password in the docker command line. 

https://hub.docker.com/r/bitping/bitping-node

From the code mentioned below, email address and password option seems to be enabled in the app by default.

https://github.com/technotiger/CashReaper/blob/main/rootfs/bin/bitping_service

Thank you

**Comment by yanhao98** [comment]
+1

**Comment by Firaenix** [comment]
We already support email, password and MFA code via command line

```
❯ bitpingd login --help
Log into Bitping

Usage: bitpingd login [OPTIONS]

Options:
  -e, --email <EMAIL>        Log in with username and password - Non Interactive
  -p, --password <PASSWORD>  Log in with username and password - Non Interactive
  -m, --mfa-code <MFA_CODE>  Log in with username and password + MFA Code if set up - Non Interactive
  -h, --help                 Print help
 ```
 
 If you want to do this via docker you could override the entrypoint like so
 
 ```docker run -it --mount type=volume,source="bitpingd-volume",target=/root/.bitpingd --entrypoint /app/bitpingd bitping/bitpingd:latest login --email "test@test.com" --password "test"```
 
 And then once its logged in successfully, run
 
 ```docker run -it --mount type=volume,source="bitpingd-volume",target=/root/.bitpingd bitping/bitpingd:latest```
 
 Let me know if you have any further issues

**Comment by engageub** [comment]
Hi @Firaenix ,
Thank you for the response. The mentioned commands work fine for docker. 

Thank you

**Comment by engageub** [comment]
Hi @Firaenix ,
Can I copy the same folder bitpingd-volume on other hosts also or do I have to create new volumes on each host.
Does the volume contain data only related to credentials or some new Ids are generated in the database. 
Thank you
